### ISSUE TITLE
ERROR: No such file or directory

### ISSUE THREAD

**Issue by Odeioikr** [pcrbot/YoCool-Console#10]
大佬好，我没有编程方面很深的知识，只是出于兴趣搭建了一个机器人
我使用的是源码版yobot，在配置YoCool-Console的时候也根据reademe在config下copy了一个配置文件，hoshino启动时也提示成功为YoCool-Console加载了config 但是在使用一键安装命令后会出现如下错误
```
[2021-04-26 09:13:20,635 nonebot] ERROR: An exception occurred while running command ('一键安装',):
[2021-04-26 09:13:20,635 nonebot] ERROR: [Errno 2] No such file or directory: './hoshino/modules/yobot/yobot/src/client/public'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/shutil.py", line 806, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: './hoshino/modules/yobot/yobot/src/client/public' -> '/root/HoshinoBot/hoshino/modules/YoCool-Console/backup/public'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/command/__init__.py", line 881, in _real_run_command
    await asyncio.wait_for(future, timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/nonebot/command/__init__.py", line 173, in run
    await self.func(session)
  File "/root/HoshinoBot/hoshino/modules/YoCool-Console/yocool.py", line 273, in one_key_yocool
    status, version, updatenote = await update_yocool(force=True)
  File "/root/HoshinoBot/hoshino/modules/YoCool-Console/yocool.py", line 185, in update_yocool
    shutil.move(yobot_themes_path,backup_themes_path)
  File "/usr/local/lib/python3.9/shutil.py", line 820, in move
    copy_function(src, real_dst)
  File "/usr/local/lib/python3.9/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: './hoshino/modules/yobot/yobot/src/client/public'

```
看起来好像是YoCool-Console将yobot当做插件版来进行安装了，请问要怎么解决这个问题呢？不胜感激

**Comment by Odeioikr** [comment]
另外，运行机器人主程序时也是在/HoshinoBot这个目录下使用 ‘python3 run.py’运行的

**Comment by Odeioikr** [comment]
附error前的log
```
[2021-04-26 09:27:30,646 nonebot] INFO: Self: 2033460171, Message -1343098014 from 1304459456: '一键安装'
[2021-04-26 09:27:30,648 hoshino] INFO: 正在进行安装前初始化
[2021-04-26 09:27:31,069 hoshino] INFO: 当前最新YoCool版本：YoCool-v1.1.5
[2021-04-26 09:27:31,070 hoshino] INFO: 本地YoCool版本：YoCool-v1.1.5
[2021-04-26 09:27:31,070 hoshino] INFO: 检查本地主题配置
[2021-04-26 09:27:31,070 hoshino] INFO: 本地主题当前配置：PrincessAdventure
[2021-04-26 09:27:31,071 hoshino] INFO: 开始下载YoCool主题PrincessAdventure
[2021-04-26 09:27:32,455 hoshino] INFO: 开始解压缩主题文件
[2021-04-26 09:27:32,549 hoshino] INFO: 主题文件解压完成
[2021-04-26 09:27:32,550 hoshino] INFO: 主题文件准备完毕！
[2021-04-26 09:27:32,550 hoshino] INFO: 检查YoCool安装状态
[2021-04-26 09:27:32,551 hoshino] INFO: 正在备份yobot原生主题文件
[2021-04-26 09:27:32,551 nonebot] ERROR: An exception occurred while running command ('一键安装',):
[2021-04-26 09:27:32,552 nonebot] ERROR: [Errno 2] No such file or directory: './hoshino/modules/yobot/yobot/src/client/public'
Traceback (most recent call last):

```

**Comment by lzx722** [comment]
你的yobot不是插件版吧，一个可以偷懒的办法是修改第22行，``   yobot_path = './hoshino/modules/yobot/yobot/'  ``，把真正的地址填进去

**Comment by Odeioikr** [comment]
> 
> 
> 你的yobot不是插件版吧，一个可以偷懒的办法是修改第22行，` yobot_path = './hoshino/modules/yobot/yobot/' `，把真正的地址填进去

好的，我试下

**Comment by Odeioikr** [comment]
> 
> 
> 你的yobot不是插件版吧，一个可以偷懒的办法是修改第22行，` yobot_path = './hoshino/modules/yobot/yobot/' `，把真正的地址填进去

谢谢大佬，已经成功了，之前感觉像是配置文件没有正常生效

**Comment by A-kirami** [comment]
已在新版本中修复该问题
