### ISSUE TITLE
安装插件的小bug2

### ISSUE THREAD

**Issue by yuban01652** [pcrbot/YoCool-Console#3]
大佬我又来了_(:з」∠)_
插件版安装yocool时，会报错，并且会导致yobot的public文件夹整个消失。我的插件文件夹名称是yocool。
报错文件：
[2020-11-17 16:02:31,462 hoshino] INFO: 正在备份yobot原生主题文件
[2020-11-17 16:02:31,467 hoshino] INFO: 正在写入YoCool主题文件
[2020-11-17 16:02:33,931 nonebot] ERROR: An exception occurred while running command ('一键安装',):
[2020-11-17 16:02:33,932 nonebot] ERROR: [Errno 2] No such file or directory: '/root/HoshinoBot/hoshino/modules/yocool/public'
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/shutil.py", line 788, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/root/HoshinoBot/hoshino/modules/yocool/public' -> './hoshino/modules/yobot/yobot/src/client/public'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/command/__init__.py", line 723, in _real_run_command
    await asyncio.wait_for(future, timeout)
  File "/usr/local/python3/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/command/__init__.py", line 101, in run
    await self.func(session)
  File "/root/HoshinoBot/hoshino/modules/yocool/yocool.py", line 273, in one_key_yocool
    status, version, updatenote = await update_yocool(force=True)
  File "/root/HoshinoBot/hoshino/modules/yocool/yocool.py", line 189, in update_yocool
    shutil.move(yocool_themes_path,yobot_themes_path)        <--我猜问题是这个
  File "/usr/local/python3/lib/python3.8/shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "/usr/local/python3/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/python3/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/root/HoshinoBot/hoshino/modules/yocool/public'
[2020-11-17 16:02:33,932 nonebot] INFO: Message -1609836341 is handled as a command

经过检查，不知为啥压缩文件没有被解压，可能是压缩文件名不对
我这边下载下来的压缩文件名称是yocoolpublic.zip

**Comment by A-kirami** [comment]
该问题已经修复，感谢反馈
