### ISSUE TITLE
使用插件的小bug3

### ISSUE THREAD

**Issue by yuban01652** [pcrbot/YoCool-Console#4]
感谢大佬，但是还是我_(:з」∠)_
这次是切换主题 2的命令报错，一键安装 2也一样，是不是其他主题没法下载啊？
另外报错信息是没有hoshino.error这种方法，好像只有hoshino.logger.error
报错信息：
[2020-11-19 15:34:37,672 nonebot] INFO: Self: 2478965279, Message -1209329155 from 493093050: '切换主题 2'
[2020-11-19 15:34:37,673 hoshino] INFO: 设置YoCool主题为CoolLite
[2020-11-19 15:34:43,009 hoshino] INFO: 当前最新YoCool版本：YoCool-v1.1.2
[2020-11-19 15:34:43,009 hoshino] INFO: 本地YoCool版本：YoCool-v1.1.2
[2020-11-19 15:34:43,009 hoshino] INFO: 检查本地主题配置
[2020-11-19 15:34:43,009 hoshino] INFO: 本地主题当前配置：CoolLite
[2020-11-19 15:34:43,009 hoshino] INFO: 开始下载YoCool主题CoolLite
[2020-11-19 15:34:50,639 hoshino] ERROR: 下载YoCool最新版本时发生错误404
[2020-11-19 15:34:50,640 nonebot] ERROR: An exception occurred while running command ('切换主题',):
[2020-11-19 15:34:50,641 nonebot] ERROR: module 'hoshino' has no attribute 'error'
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/command/__init__.py", line 723, in _real_run_command
    await asyncio.wait_for(future, timeout)
  File "/usr/local/python3/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/command/__init__.py", line 101, in run
    await self.func(session)
  File "/root/HoshinoBot/hoshino/modules/yocool/yocool.py", line 310, in set_yocool_themes
    await update_yocool(force=True)
  File "/root/HoshinoBot/hoshino/modules/yocool/yocool.py", line 178, in update_yocool
    hoshino.error(f'下载YoCool文件时发生错误')
AttributeError: module 'hoshino' has no attribute 'error'

**Comment by A-kirami** [comment]
这个问题是由于yocool那边目前只有一个主题，第二个主题尚在开发中，只是控制台预留了一个接口以备主题更新之后使用，因此实际上是无法使用的
