### ISSUE TITLE
最新版yobot插件版安装yocool后提示缺少文件

### ISSUE THREAD

**Issue by yuban01652** [pcrbot/YoCool-Console#6]
大佬又是我_(:з」∠)_
linux系统，git最新版yobot，作为hoshinobot插件版（未测试源码版），最新版yocool，安装后无法登陆，如果保留登录cookie的话，用户管理、公会管理之类会提示Intenet Server Error
报错信息：
[2020-12-30 20:55:56,271] ERROR in app: Exception on request GET /yobot/admin/users/
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/quart/app.py", line 1807, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/usr/local/python3/lib/python3.8/site-packages/quart/app.py", line 1829, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/usr/local/python3/lib/python3.8/site-packages/quart/app.py", line 1074, in handle_user_exception
    raise error
  File "/usr/local/python3/lib/python3.8/site-packages/quart/app.py", line 1827, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/local/python3/lib/python3.8/site-packages/quart/app.py", line 1875, in dispatch_request
    return await handler(**request_.view_args)
  File "/root/HoshinoBot/hoshino/modules/yobot/yobot/src/client/ybplugins/settings.py", line 224, in yobot_users_managing
    return await render_template('admin/users.html')
  File "/root/HoshinoBot/hoshino/modules/yobot/yobot/src/client/ybplugins/templating.py", line 29, in render_template
    t = _env.get_template(template)
  File "/usr/local/python3/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/python3/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/python3/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/python3/lib/python3.8/site-packages/jinja2/loaders.py", line 197, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: admin/users.html

久违的更新了yobot结果yocool就用不了了，除了yobot更新外没做过更改。

看上去yocool的1.1.3虽然支持了yobot最新版，但是因为备份使用的是move，并且yocool的安装文件里只有修改过的文件，导致public/static目录下不用修改的文件丢失。

大概备份改成复制，然后新文件强制覆盖之类的就好了吧_(:з」∠)_

**Comment by A-kirami** [comment]
看了一下发现上传错压缩包了……之后重新上传一个新包
